import os
from building import *

cwd = GetCurrentDir()

# Add source code
src = Glob('*.cc')
src += Glob('models/*.cc')
inc = [cwd]

CPPDEFINES = ['CMSIS_DEVICE_ARM_CORTEX_M_XX_HEADER_FILE=\'core_cm33.h\'']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = inc, CPPDEFINES=CPPDEFINES)

Return('group')
