import os
from building import *

cwd = GetCurrentDir()

# Add source code
src = Glob('*.c')
src += Glob('*.cc')
src += Glob('Audio/*.cc')
inc = [cwd, cwd+'/Include']
Import('SIFLI_SDK')

CPPDEFINES = ['CMSIS_DEVICE_ARM_CORTEX_M_XX_HEADER_FILE=\"<register.h>\"', 'CMSIS_NN', 'ARM_DSP']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = inc, CPPDEFINES=CPPDEFINES)

group.extend(SConscript(os.path.join(cwd,'../../SConscript'),variant_dir="tflite", duplicate=0))

# Add SDK
group.extend(SConscript(os.path.join(SIFLI_SDK, 'SConscript'), variant_dir="sifli_sdk", duplicate=0))

Return('group')
