import os
from building import *

cwd = GetCurrentDir()

# Add source code
src = Glob('*.cc')
src += Glob('*.c')
src += Glob('models/*.cc')
src += Glob('testdata/*.cc')
inc = [cwd]

CPPDEFINES = ['CMSIS_DEVICE_ARM_CORTEX_M_XX_HEADER_FILE=\"<register.h>\"', 'CMSIS_NN']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = inc, CPPDEFINES=CPPDEFINES)

Return('group')
